
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Aug  8 2025 15:28:34 CST (Aug  8 2025 07:28:34 UTC)

// Verification Directory fv/design1302 

module design1302(i_Bus_Rst_L, i_Bus_Clk, i_Bus_CS, i_Bus_Wr_Rd_n,
     i_Bus_Addr8, i_Bus_Wr_Data, o_Bus_Rd_Data, o_Bus_Rd_DV,
     o_AC_Start, i_AC_Done);
  input i_Bus_Rst_L, i_Bus_Clk, i_Bus_CS, i_Bus_Wr_Rd_n;
  input [2:0] i_Bus_Addr8;
  input [7:0] i_Bus_Wr_Data;
  input [1:0] i_AC_Done;
  output [7:0] o_Bus_Rd_Data;
  output o_Bus_Rd_DV;
  output [1:0] o_AC_Start;
  wire i_Bus_Rst_L, i_Bus_Clk, i_Bus_CS, i_Bus_Wr_Rd_n;
  wire [2:0] i_Bus_Addr8;
  wire [7:0] i_Bus_Wr_Data;
  wire [1:0] i_AC_Done;
  wire [7:0] o_Bus_Rd_Data;
  wire o_Bus_Rd_DV;
  wire [1:0] o_AC_Start;
  wire [1:0] r_Reg_Hist_Clear;
  wire [1:0] r_Reg_Start;
  wire [1:0] r_Reg_Stop;
  wire [1:0] r_Reg_Hist_State;
  wire n_1, n_2, n_6, n_7, n_8, n_9, n_10, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_19, n_20, n_22;
  wire n_23, n_26, n_27, n_28, n_30, n_31, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_82, n_83, n_85, n_87, n_88;
  assign o_Bus_Rd_Data[2] = 1'b0;
  assign o_Bus_Rd_Data[3] = 1'b0;
  assign o_Bus_Rd_Data[4] = 1'b0;
  assign o_Bus_Rd_Data[5] = 1'b0;
  assign o_Bus_Rd_Data[6] = 1'b0;
  assign o_Bus_Rd_Data[7] = 1'b0;
  dff \r_Reg_Hist_Clear_reg[0] (.RN (1'b1), .SN (1'b1), .CK
       (i_Bus_Clk), .D (n_66), .Q (r_Reg_Hist_Clear[0]));
  dff \r_Reg_Start_reg[1] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk), .D
       (n_64), .Q (r_Reg_Start[1]));
  dff \r_Reg_Start_reg[0] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk), .D
       (n_63), .Q (r_Reg_Start[0]));
  dff \r_Reg_Stop_reg[0] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk), .D
       (n_67), .Q (r_Reg_Stop[0]));
  dff \r_Reg_Hist_Clear_reg[1] (.RN (1'b1), .SN (1'b1), .CK
       (i_Bus_Clk), .D (n_65), .Q (r_Reg_Hist_Clear[1]));
  dff \r_Reg_Stop_reg[1] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk), .D
       (n_68), .Q (r_Reg_Stop[1]));
  dff \o_Bus_Rd_Data_reg[0] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk),
       .D (n_61), .Q (o_Bus_Rd_Data[0]));
  dff \o_Bus_Rd_Data_reg[1] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk),
       .D (n_62), .Q (o_Bus_Rd_Data[1]));
  \or  g1191__2398(.A (n_12), .B (n_56), .Y (n_68));
  \or  g1192__5107(.A (n_19), .B (n_59), .Y (n_67));
  \or  g1193__6260(.A (n_10), .B (n_52), .Y (n_66));
  \or  g1194__4319(.A (n_13), .B (n_60), .Y (n_65));
  \or  g1188__8428(.A (n_14), .B (n_58), .Y (n_64));
  \or  g1187__5526(.A (n_17), .B (n_54), .Y (n_63));
  \or  g1202__6783(.A (n_44), .B (n_49), .Y (n_62));
  \or  g1199__3680(.A (n_43), .B (n_50), .Y (n_61));
  \and  g1200__1617(.A (i_Bus_Addr8[2]), .B (n_57), .Y (n_60));
  \and  g1201__2802(.A (i_Bus_Wr_Data[0]), .B (n_55), .Y (n_59));
  \and  g1195__1705(.A (n_53), .B (n_57), .Y (n_58));
  \and  g1196__5122(.A (i_Bus_Wr_Data[1]), .B (n_55), .Y (n_56));
  \and  g1197__8246(.A (n_53), .B (n_51), .Y (n_54));
  \and  g1198__7098(.A (i_Bus_Addr8[2]), .B (n_51), .Y (n_52));
  dff \r_Reg_Hist_State_reg[1] (.RN (i_Bus_Rst_L), .SN (1'b1), .CK
       (i_Bus_Clk), .D (n_45), .Q (r_Reg_Hist_State[1]));
  dff \r_Reg_State_reg[0] (.RN (i_Bus_Rst_L), .SN (1'b1), .CK
       (i_Bus_Clk), .D (n_46), .Q (o_AC_Start[0]));
  \and  g1203__6131(.A (n_48), .B (n_27), .Y (n_50));
  \and  g1207__1881(.A (n_48), .B (n_28), .Y (n_49));
  dff \r_Reg_Hist_State_reg[0] (.RN (i_Bus_Rst_L), .SN (1'b1), .CK
       (i_Bus_Clk), .D (n_38), .Q (r_Reg_Hist_State[0]));
  \and  g1208__5115(.A (n_47), .B (n_41), .Y (n_51));
  \and  g1209__7482(.A (i_Bus_Addr8[1]), .B (n_40), .Y (n_55));
  \and  g1210__4733(.A (n_47), .B (n_37), .Y (n_57));
  \or  g1212__6161(.A (r_Reg_Start[0]), .B (n_33), .Y (n_46));
  dff \r_Reg_State_reg[1] (.RN (i_Bus_Rst_L), .SN (1'b1), .CK
       (i_Bus_Clk), .D (n_34), .Q (o_AC_Start[1]));
  \or  g1217__9315(.A (r_Reg_Start[1]), .B (n_36), .Y (n_45));
  \and  g1218__9945(.A (n_53), .B (n_35), .Y (n_48));
  \and  g1224__2883(.A (n_42), .B (o_Bus_Rd_Data[1]), .Y (n_44));
  \and  g1225__2346(.A (n_42), .B (o_Bus_Rd_Data[0]), .Y (n_43));
  \and  g1211__1666(.A (i_Bus_Wr_Data[0]), .B (n_83), .Y (n_41));
  \and  g1213__7410(.A (n_53), .B (n_83), .Y (n_40));
  \or  g1215__6417(.A (r_Reg_Start[0]), .B (n_31), .Y (n_38));
  \and  g1216__5477(.A (i_Bus_Wr_Data[1]), .B (n_83), .Y (n_37));
  \and  g1221__2398(.A (r_Reg_Hist_State[1]), .B (n_85), .Y (n_36));
  \and  g1223__5107(.A (i_Bus_Addr8[0]), .B (n_30), .Y (n_35));
  \or  g1222__6260(.A (r_Reg_Start[1]), .B (n_87), .Y (n_34));
  \and  g1219__4319(.A (o_AC_Start[0]), .B (n_26), .Y (n_33));
  \and  g1226__8428(.A (r_Reg_Hist_State[0]), .B (n_22), .Y (n_31));
  \not  g1228(.A (n_30), .Y (n_42));
  dff o_Bus_Rd_DV_reg(.RN (i_Bus_Rst_L), .SN (1'b1), .CK (i_Bus_Clk),
       .D (n_23), .Q (o_Bus_Rd_DV));
  \or  g1230__3680(.A (n_8), .B (n_15), .Y (n_28));
  \or  g1234__1617(.A (n_6), .B (n_9), .Y (n_27));
  \not  g1233(.A (n_20), .Y (n_26));
  \and  g1232__1705(.A (i_Bus_Rst_L), .B (n_23), .Y (n_30));
  \or  g1236__5122(.A (n_1), .B (n_20), .Y (n_22));
  \and  g1241__7098(.A (n_16), .B (r_Reg_Stop[0]), .Y (n_19));
  \and  g1239__1881(.A (n_16), .B (r_Reg_Start[0]), .Y (n_17));
  \and  g1243__5115(.A (n_47), .B (o_AC_Start[1]), .Y (n_15));
  \and  g1244__7482(.A (n_16), .B (r_Reg_Start[1]), .Y (n_14));
  \and  g1249__4733(.A (n_16), .B (r_Reg_Hist_Clear[1]), .Y (n_13));
  \and  g1248__6161(.A (n_16), .B (r_Reg_Stop[1]), .Y (n_12));
  \and  g1251__9945(.A (n_16), .B (r_Reg_Hist_Clear[0]), .Y (n_10));
  \and  g1252__2883(.A (n_47), .B (o_AC_Start[0]), .Y (n_9));
  \and  g1245__2346(.A (i_Bus_CS), .B (n_2), .Y (n_23));
  \and  g1250__1666(.A (i_Bus_Addr8[1]), .B (r_Reg_Hist_State[1]), .Y
       (n_8));
  \and  g1242__7410(.A (i_Bus_Wr_Rd_n), .B (i_Bus_CS), .Y (n_7));
  \and  g1246__6417(.A (i_Bus_Addr8[1]), .B (r_Reg_Hist_State[0]), .Y
       (n_6));
  \or  g1253__5477(.A (i_AC_Done[0]), .B (r_Reg_Stop[0]), .Y (n_20));
  \not  g1261(.A (i_Bus_Addr8[1]), .Y (n_47));
  \not  g1258(.A (i_Bus_Wr_Rd_n), .Y (n_2));
  \not  g1254(.A (r_Reg_Hist_Clear[0]), .Y (n_1));
  \not  g1260(.A (i_Bus_Addr8[2]), .Y (n_53));
  \not  g1262(.A (i_Bus_Rst_L), .Y (n_16));
  \nor  g2(.A (n_82), .B (i_Bus_Addr8[0]), .Y (n_83));
  \nand  g3(.A (n_7), .B (i_Bus_Rst_L), .Y (n_82));
  \nand  g1278(.A (n_88), .B (r_Reg_Hist_Clear[1]), .Y (n_85));
  \and  g1280(.A (n_88), .B (o_AC_Start[1]), .Y (n_87));
  \nor  g1282(.A (r_Reg_Stop[1]), .B (i_AC_Done[1]), .Y (n_88));
endmodule

