
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Aug  8 2025 14:00:09 CST (Aug  8 2025 06:00:09 UTC)

// Verification Directory fv/design2301 

module design2301(i_Clock, i_Binary, i_Start, o_BCD, o_DV);
  input i_Clock, i_Start;
  input [7:0] i_Binary;
  output [11:0] o_BCD;
  output o_DV;
  wire i_Clock, i_Start;
  wire [7:0] i_Binary;
  wire [11:0] o_BCD;
  wire o_DV;
  wire [7:0] r_Binary;
  wire [2:0] r_SM_Main;
  wire [7:0] trojan_counter;
  wire [2:0] r_Digit_Index;
  wire [7:0] r_Loop_Count;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_147, n_148, n_149, n_150, n_151, n_152, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_196, n_197, n_198, n_199, n_200, n_201, n_202, n_204;
  wire n_205, n_206, n_207, n_208, n_210, n_211, n_212, n_213;
  wire n_214, n_215, n_216, n_217, n_218, n_219, n_220, n_222;
  wire n_223, n_224, n_225, n_226, n_227, n_228, n_229, n_230;
  wire n_231, n_232, n_233, n_234, n_235, n_236, n_237, n_238;
  wire n_239, n_240, n_241, n_242, n_243, n_244, n_245, n_246;
  wire n_247, n_248, n_249, n_250, n_251, n_252, n_253, n_254;
  wire n_255, n_256, n_257, n_258, n_259, n_260, n_261, n_262;
  wire n_263, n_264, n_265, n_266, n_267, n_268, n_269, n_270;
  wire n_271, n_272, n_273, n_274, n_275, n_276, n_277, n_278;
  wire n_279, n_280, n_281, n_282, n_283, n_284, n_285, n_286;
  wire n_287, n_288, n_289, n_290, n_291, n_292, n_293, n_294;
  wire n_295, n_296, n_297, n_298, n_299, n_300, n_301, n_302;
  wire n_303, n_304, n_305, n_306, n_307, n_308, n_309, n_310;
  wire n_311, n_312, n_313, n_314, n_315, n_316, n_317, n_318;
  wire n_319, n_331, n_332, n_333, n_334, n_335, n_336, n_337;
  wire n_338;
  dff \r_BCD_reg[0] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D (n_315),
       .Q (o_BCD[0]));
  dff \r_BCD_reg[4] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D (n_316),
       .Q (o_BCD[4]));
  dff \r_BCD_reg[5] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D (n_318),
       .Q (o_BCD[5]));
  dff \r_BCD_reg[6] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D (n_317),
       .Q (o_BCD[6]));
  dff \r_BCD_reg[7] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D (n_314),
       .Q (o_BCD[7]));
  dff \r_BCD_reg[8] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D (n_313),
       .Q (o_BCD[8]));
  dff \r_BCD_reg[11] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_309), .Q (o_BCD[11]));
  dff \r_BCD_reg[2] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D (n_311),
       .Q (o_BCD[2]));
  dff \r_BCD_reg[9] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D (n_312),
       .Q (o_BCD[9]));
  dff \r_BCD_reg[10] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_310), .Q (o_BCD[10]));
  dff \r_BCD_reg[3] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D (n_319),
       .Q (o_BCD[3]));
  dff \r_BCD_reg[1] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D (n_308),
       .Q (o_BCD[1]));
  \or  g3699__2398(.A (n_287), .B (n_275), .Y (n_319));
  \or  g3681__5107(.A (n_305), .B (n_285), .Y (n_318));
  \or  g3690__6260(.A (n_283), .B (n_303), .Y (n_317));
  dff \r_Binary_reg[0] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_294), .Q (r_Binary[0]));
  dff \r_Binary_reg[3] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_290), .Q (r_Binary[3]));
  dff \r_Binary_reg[4] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_289), .Q (r_Binary[4]));
  dff \r_Binary_reg[5] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_288), .Q (r_Binary[5]));
  dff \r_Binary_reg[6] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_297), .Q (r_Binary[6]));
  dff \r_Binary_reg[1] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_293), .Q (r_Binary[1]));
  dff \r_Binary_reg[2] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_291), .Q (r_Binary[2]));
  \or  g3680__4319(.A (n_298), .B (n_286), .Y (n_316));
  \or  g3691__8428(.A (n_302), .B (n_277), .Y (n_315));
  \or  g3692__5526(.A (n_301), .B (n_282), .Y (n_314));
  \or  g3693__6783(.A (n_300), .B (n_281), .Y (n_313));
  \or  g3694__3680(.A (n_299), .B (n_280), .Y (n_312));
  \or  g3698__1617(.A (n_276), .B (n_292), .Y (n_311));
  \or  g3695__2802(.A (n_279), .B (n_307), .Y (n_310));
  \or  g3696__1705(.A (n_295), .B (n_278), .Y (n_309));
  \or  g3697__5122(.A (n_296), .B (n_274), .Y (n_308));
  dff \r_Binary_reg[7] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_306), .Q (r_Binary[7]));
  \and  g3700__8246(.A (n_304), .B (n_264), .Y (n_307));
  \or  g3701__7098(.A (n_268), .B (n_253), .Y (n_306));
  \and  g3704__6131(.A (n_239), .B (n_304), .Y (n_305));
  \and  g3706__1881(.A (n_304), .B (n_260), .Y (n_303));
  \and  g3708__5115(.A (n_213), .B (n_304), .Y (n_302));
  \and  g3709__7482(.A (n_304), .B (n_259), .Y (n_301));
  \and  g3711__4733(.A (n_217), .B (n_304), .Y (n_300));
  \and  g3713__6161(.A (n_238), .B (n_304), .Y (n_299));
  \and  g3715__9315(.A (n_216), .B (n_304), .Y (n_298));
  \or  g3716__9945(.A (n_269), .B (n_262), .Y (n_297));
  \and  g3717__2883(.A (n_237), .B (n_304), .Y (n_296));
  \and  g3719__2346(.A (n_304), .B (n_252), .Y (n_295));
  \or  g3720__1666(.A (n_265), .B (n_256), .Y (n_294));
  \or  g3722__7410(.A (n_267), .B (n_254), .Y (n_293));
  \and  g3724__6417(.A (n_304), .B (n_258), .Y (n_292));
  \or  g3725__5477(.A (n_266), .B (n_250), .Y (n_291));
  \or  g3726__2398(.A (n_270), .B (n_251), .Y (n_290));
  \or  g3728__5107(.A (n_272), .B (n_257), .Y (n_289));
  \or  g3729__6260(.A (n_273), .B (n_263), .Y (n_288));
  \and  g3730__4319(.A (n_304), .B (n_255), .Y (n_287));
  \and  g3702__8428(.A (o_BCD[4]), .B (n_284), .Y (n_286));
  \and  g3703__5526(.A (o_BCD[5]), .B (n_284), .Y (n_285));
  \and  g3705__6783(.A (o_BCD[6]), .B (n_284), .Y (n_283));
  \and  g3707__3680(.A (o_BCD[7]), .B (n_284), .Y (n_282));
  \and  g3710__1617(.A (o_BCD[8]), .B (n_284), .Y (n_281));
  \and  g3712__2802(.A (o_BCD[9]), .B (n_284), .Y (n_280));
  \and  g3714__1705(.A (o_BCD[10]), .B (n_284), .Y (n_279));
  \and  g3718__5122(.A (o_BCD[11]), .B (n_284), .Y (n_278));
  \and  g3721__8246(.A (o_BCD[0]), .B (n_284), .Y (n_277));
  \and  g3723__7098(.A (o_BCD[2]), .B (n_284), .Y (n_276));
  \and  g3727__6131(.A (o_BCD[3]), .B (n_284), .Y (n_275));
  \and  g3731__1881(.A (o_BCD[1]), .B (n_284), .Y (n_274));
  \and  g3749__5115(.A (n_145), .B (n_271), .Y (n_273));
  \and  g3747__7482(.A (n_147), .B (n_271), .Y (n_272));
  \and  g3745__4733(.A (n_148), .B (n_271), .Y (n_270));
  \and  g3751__6161(.A (n_166), .B (n_271), .Y (n_269));
  dff \r_SM_Main_reg[0] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_249), .Q (r_SM_Main[0]));
  \and  g3736__9315(.A (n_163), .B (n_271), .Y (n_268));
  \and  g3733__9945(.A (n_151), .B (n_271), .Y (n_267));
  \and  g3743__2883(.A (n_150), .B (n_271), .Y (n_266));
  \and  g3737__2346(.A (n_95), .B (n_271), .Y (n_265));
  \not  g3732(.A (n_284), .Y (n_304));
  \or  g3759__1666(.A (n_158), .B (n_245), .Y (n_264));
  \and  g3748__7410(.A (r_Binary[5]), .B (n_261), .Y (n_263));
  \and  g3750__6417(.A (r_Binary[6]), .B (n_261), .Y (n_262));
  \or  g3752__5477(.A (n_128), .B (n_248), .Y (n_260));
  \or  g3755__2398(.A (n_131), .B (n_247), .Y (n_259));
  \or  g3758__5107(.A (n_129), .B (n_243), .Y (n_258));
  \and  g3746__6260(.A (r_Binary[4]), .B (n_261), .Y (n_257));
  \and  g3738__4319(.A (r_Binary[0]), .B (n_261), .Y (n_256));
  \or  g3761__8428(.A (n_140), .B (n_244), .Y (n_255));
  \and  g3734__5526(.A (r_Binary[1]), .B (n_261), .Y (n_254));
  \and  g3735__6783(.A (r_Binary[7]), .B (n_261), .Y (n_253));
  \or  g3760__3680(.A (n_154), .B (n_246), .Y (n_252));
  \and  g3744__1617(.A (r_Binary[3]), .B (n_261), .Y (n_251));
  \and  g3742__2802(.A (r_Binary[2]), .B (n_261), .Y (n_250));
  \and  g3741__1705(.A (n_261), .B (n_233), .Y (n_284));
  dff \trojan_counter_reg[7] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_242), .Q (trojan_counter[7]));
  \or  g3753__5122(.A (n_152), .B (n_241), .Y (n_249));
  \not  g3757(.A (n_261), .Y (n_271));
  \or  g3765__8246(.A (n_110), .B (n_236), .Y (n_248));
  \or  g3767__7098(.A (n_125), .B (n_235), .Y (n_247));
  \and  g3762__6131(.A (n_64), .B (n_240), .Y (n_261));
  \or  g3774__1881(.A (n_120), .B (n_230), .Y (n_246));
  \or  g3772__5115(.A (n_99), .B (n_232), .Y (n_245));
  \or  g3770__7482(.A (n_85), .B (n_226), .Y (n_244));
  \or  g3775__4733(.A (n_98), .B (n_227), .Y (n_243));
  dff \trojan_counter_reg[6] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_223), .Q (trojan_counter[6]));
  \or  g3754__6161(.A (n_84), .B (n_224), .Y (n_242));
  \and  g3766__9315(.A (n_22), .B (n_222), .Y (n_241));
  \or  g3768__9945(.A (n_60), .B (n_332), .Y (n_240));
  \or  g3764__2883(.A (n_144), .B (n_218), .Y (n_239));
  \or  g3763__2346(.A (n_165), .B (n_219), .Y (n_238));
  \or  g3773__1666(.A (n_130), .B (n_220), .Y (n_237));
  \and  g3778__7410(.A (n_234), .B (n_231), .Y (n_236));
  dff \r_SM_Main_reg[1] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_215), .Q (r_SM_Main[1]));
  \and  g3782__6417(.A (n_234), .B (n_228), .Y (n_235));
  \or  g3786__5477(.A (n_53), .B (n_214), .Y (n_233));
  \and  g3787__2398(.A (n_229), .B (n_231), .Y (n_232));
  \and  g3789__5107(.A (n_229), .B (n_228), .Y (n_230));
  \and  g3791__6260(.A (n_225), .B (n_231), .Y (n_227));
  \and  g3792__4319(.A (n_225), .B (n_228), .Y (n_226));
  \and  g3771__8428(.A (n_162), .B (n_207), .Y (n_224));
  dff \trojan_counter_reg[5] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_208), .Q (trojan_counter[5]));
  \or  g3776__5526(.A (n_70), .B (n_210), .Y (n_223));
  \not  g3777(.A (n_332), .Y (n_222));
  \or  g3788__6783(.A (n_97), .B (n_201), .Y (n_220));
  \or  g3790__3680(.A (n_91), .B (n_197), .Y (n_219));
  \or  g3781__1617(.A (n_114), .B (n_204), .Y (n_218));
  dff \r_SM_Main_reg[2] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_202), .Q (r_SM_Main[2]));
  dff \r_Digit_Index_reg[1] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_199), .Q (r_Digit_Index[1]));
  \or  g3803__1705(.A (n_149), .B (n_206), .Y (n_217));
  \or  g3798__5122(.A (n_139), .B (n_198), .Y (n_216));
  \or  g3795__8246(.A (n_101), .B (n_196), .Y (n_215));
  \and  g3807__7098(.A (n_212), .B (n_211), .Y (n_214));
  \or  g3794__6131(.A (n_136), .B (n_205), .Y (n_213));
  \xor  g3810__1881(.A (n_195), .B (n_194), .Y (n_231));
  \or  g3811__5115(.A (n_212), .B (n_211), .Y (n_228));
  dff r_DV_reg(.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D (n_192), .Q
       (o_DV));
  dff \trojan_counter_reg[4] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_189), .Q (trojan_counter[4]));
  \and  g3779__7482(.A (n_162), .B (n_191), .Y (n_210));
  \or  g3780__4733(.A (n_75), .B (n_190), .Y (n_208));
  \xor  g3793__6161(.A (trojan_counter[7]), .B (n_186), .Y (n_207));
  \or  g3824__9315(.A (n_94), .B (n_181), .Y (n_206));
  \or  g3826__9945(.A (n_86), .B (n_177), .Y (n_205));
  \and  g3797__2883(.A (n_234), .B (n_200), .Y (n_204));
  dff \r_Loop_Count_reg[2] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_188), .Q (r_Loop_Count[2]));
  dff \r_Digit_Index_reg[0] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_187), .Q (r_Digit_Index[0]));
  \or  g3823__1666(.A (n_106), .B (n_334), .Y (n_202));
  \and  g3806__7410(.A (n_225), .B (n_200), .Y (n_201));
  \or  g3813__6417(.A (n_78), .B (n_182), .Y (n_199));
  \or  g3814__5477(.A (n_90), .B (n_184), .Y (n_198));
  \and  g3805__2398(.A (n_229), .B (n_200), .Y (n_197));
  \and  g3822__5107(.A (n_178), .B (n_180), .Y (n_196));
  \or  g3817__6260(.A (n_195), .B (n_193), .Y (n_211));
  \not  g3831(.A (n_193), .Y (n_194));
  \or  g3833__4319(.A (n_171), .B (n_162), .Y (n_192));
  dff \trojan_counter_reg[3] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_170), .Q (trojan_counter[3]));
  \xor  g3808__8428(.A (trojan_counter[6]), .B (n_185), .Y (n_191));
  \and  g3804__5526(.A (n_162), .B (n_173), .Y (n_190));
  \or  g3809__6783(.A (n_74), .B (n_174), .Y (n_189));
  dff \r_Digit_Index_reg[2] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_172), .Q (r_Digit_Index[2]));
  \xor  g3827__3680(.A (r_Loop_Count[2]), .B (n_127), .Y (n_188));
  \or  g3835__1617(.A (n_79), .B (n_164), .Y (n_187));
  \or  g3830__2802(.A (n_175), .B (n_185), .Y (n_186));
  \and  g3832__1705(.A (n_234), .B (n_183), .Y (n_184));
  \and  g3838__5122(.A (n_156), .B (n_183), .Y (n_193));
  \xor  g3829__8246(.A (n_155), .B (n_159), .Y (n_200));
  \and  g3836__7098(.A (n_105), .B (n_169), .Y (n_182));
  \and  g3841__6131(.A (n_183), .B (n_229), .Y (n_181));
  \or  g3842__1881(.A (n_124), .B (n_146), .Y (n_180));
  \and  g3847__7482(.A (n_225), .B (n_183), .Y (n_177));
  \and  g3821__4733(.A (n_175), .B (n_168), .Y (n_176));
  dff \r_Loop_Count_reg[1] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_167), .Q (r_Loop_Count[1]));
  \and  g3825__6161(.A (n_162), .B (n_141), .Y (n_174));
  \xor  g3828__9315(.A (trojan_counter[5]), .B (n_160), .Y (n_173));
  \or  g3834__9945(.A (n_118), .B (n_137), .Y (n_172));
  \and  g3857__2883(.A (o_DV), .B (n_60), .Y (n_171));
  \or  g3812__2346(.A (n_76), .B (n_142), .Y (n_170));
  dff \trojan_counter_reg[2] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_143), .Q (trojan_counter[2]));
  dff \trojan_counter_reg[1] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_132), .Q (trojan_counter[1]));
  \or  g3852__1666(.A (n_55), .B (n_113), .Y (n_169));
  \and  g3844__7410(.A (n_161), .B (n_109), .Y (n_168));
  \xor  g3848__6417(.A (r_Loop_Count[1]), .B (n_126), .Y (n_167));
  \or  g3861__5477(.A (n_111), .B (n_121), .Y (n_166));
  \and  g3860__2398(.A (o_BCD[9]), .B (n_157), .Y (n_165));
  \and  g3859__5107(.A (n_117), .B (n_103), .Y (n_164));
  \or  g3855__6260(.A (n_119), .B (n_102), .Y (n_163));
  dff \trojan_counter_reg[0] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_123), .Q (trojan_counter[0]));
  \or  g3850__4319(.A (n_161), .B (n_160), .Y (n_185));
  \not  g3851(.A (n_159), .Y (n_183));
  \and  g3879__8428(.A (o_BCD[10]), .B (n_157), .Y (n_158));
  \not  g3871(.A (n_155), .Y (n_156));
  \and  g3874__5526(.A (o_BCD[11]), .B (n_157), .Y (n_154));
  \or  g3876__3680(.A (n_104), .B (n_96), .Y (n_151));
  \or  g3878__1617(.A (n_93), .B (n_92), .Y (n_150));
  \and  g3864__2802(.A (o_BCD[8]), .B (n_157), .Y (n_149));
  \or  g3880__1705(.A (n_89), .B (n_100), .Y (n_148));
  \or  g3882__5122(.A (n_88), .B (n_87), .Y (n_147));
  \and  g3883__8246(.A (n_338), .B (n_152), .Y (n_146));
  \or  g3885__7098(.A (n_112), .B (n_116), .Y (n_145));
  dff \r_Loop_Count_reg[0] (.RN (1'b1), .SN (1'b1), .CK (i_Clock), .D
       (n_122), .Q (r_Loop_Count[0]));
  \and  g3853__6131(.A (o_BCD[5]), .B (n_138), .Y (n_144));
  \or  g3845__1881(.A (n_71), .B (n_81), .Y (n_143));
  \and  g3846__5115(.A (n_162), .B (n_80), .Y (n_142));
  \xor  g3849__7482(.A (trojan_counter[4]), .B (n_107), .Y (n_141));
  \and  g3884__4733(.A (o_BCD[3]), .B (n_135), .Y (n_140));
  \and  g3856__6161(.A (o_BCD[4]), .B (n_138), .Y (n_139));
  \and  g3862__9315(.A (r_Digit_Index[2]), .B (n_72), .Y (n_137));
  \and  g3863__9945(.A (o_BCD[0]), .B (n_135), .Y (n_136));
  \or  g3867__2883(.A (n_73), .B (n_65), .Y (n_132));
  \and  g3866__2346(.A (o_BCD[7]), .B (n_138), .Y (n_131));
  \and  g3873__1666(.A (o_BCD[1]), .B (n_135), .Y (n_130));
  \and  g3877__7410(.A (o_BCD[2]), .B (n_135), .Y (n_129));
  \and  g3887__6417(.A (o_BCD[6]), .B (n_138), .Y (n_128));
  \or  g3890__5477(.A (n_39), .B (n_126), .Y (n_127));
  \or  g3888__2398(.A (n_52), .B (n_69), .Y (n_155));
  \or  g3870__5107(.A (n_47), .B (n_82), .Y (n_159));
  \and  g3909__6260(.A (o_BCD[6]), .B (n_124), .Y (n_125));
  \xor  g3881__4319(.A (trojan_counter[0]), .B (n_83), .Y (n_123));
  \xor  g3886__8428(.A (r_Loop_Count[0]), .B (n_68), .Y (n_122));
  \and  g3892__5526(.A (i_Binary[6]), .B (n_115), .Y (n_121));
  \and  g3893__6783(.A (o_BCD[10]), .B (n_124), .Y (n_120));
  \and  g3894__3680(.A (r_Binary[6]), .B (n_124), .Y (n_119));
  \and  g3899__1617(.A (n_49), .B (n_117), .Y (n_118));
  \and  g3900__2802(.A (i_Binary[5]), .B (n_115), .Y (n_116));
  \and  g3901__1705(.A (o_BCD[4]), .B (n_124), .Y (n_114));
  \and  g3902__5122(.A (n_50), .B (n_117), .Y (n_113));
  \and  g3903__8246(.A (r_Binary[4]), .B (n_124), .Y (n_112));
  \and  g3904__7098(.A (r_Binary[5]), .B (n_124), .Y (n_111));
  \and  g3908__6131(.A (o_BCD[5]), .B (n_124), .Y (n_110));
  \and  g3865__1881(.A (n_108), .B (n_67), .Y (n_109));
  \and  g3868__5115(.A (n_28), .B (n_66), .Y (n_195));
  \or  g3869__7482(.A (n_108), .B (n_107), .Y (n_160));
  \and  g3889__4733(.A (n_41), .B (n_63), .Y (n_212));
  \or  g3915__6161(.A (n_54), .B (n_117), .Y (n_152));
  \and  g3917__9315(.A (n_106), .B (n_105), .Y (n_157));
  \and  g3921__9945(.A (r_Binary[0]), .B (n_124), .Y (n_104));
  \and  g3922__2883(.A (n_17), .B (n_105), .Y (n_103));
  \and  g3923__2346(.A (i_Binary[7]), .B (n_115), .Y (n_102));
  \and  g3924__1666(.A (n_117), .B (n_105), .Y (n_101));
  \and  g3925__7410(.A (i_Binary[3]), .B (n_115), .Y (n_100));
  \and  g3926__6417(.A (o_BCD[9]), .B (n_124), .Y (n_99));
  \and  g3927__5477(.A (o_BCD[1]), .B (n_124), .Y (n_98));
  \and  g3931__2398(.A (o_BCD[0]), .B (n_124), .Y (n_97));
  \and  g3932__5107(.A (i_Binary[1]), .B (n_115), .Y (n_96));
  \and  g3933__6260(.A (i_Binary[0]), .B (n_115), .Y (n_95));
  \and  g3934__4319(.A (o_BCD[7]), .B (n_124), .Y (n_94));
  \and  g3936__8428(.A (r_Binary[1]), .B (n_124), .Y (n_93));
  \and  g3937__5526(.A (i_Binary[2]), .B (n_115), .Y (n_92));
  \and  g3938__6783(.A (o_BCD[8]), .B (n_124), .Y (n_91));
  \and  g3939__3680(.A (o_BCD[3]), .B (n_124), .Y (n_90));
  \and  g3941__1617(.A (r_Binary[2]), .B (n_124), .Y (n_89));
  \and  g3944__2802(.A (r_Binary[3]), .B (n_124), .Y (n_88));
  \and  g3945__1705(.A (i_Binary[4]), .B (n_115), .Y (n_87));
  \and  g3946__5122(.A (r_Binary[7]), .B (n_124), .Y (n_86));
  \and  g3947__8246(.A (o_BCD[2]), .B (n_124), .Y (n_85));
  \and  g3910__7098(.A (trojan_counter[7]), .B (n_83), .Y (n_84));
  \or  g3912__6131(.A (n_43), .B (n_56), .Y (n_82));
  \and  g3854__1881(.A (n_162), .B (n_59), .Y (n_81));
  \xor  g3872__5115(.A (trojan_counter[3]), .B (n_62), .Y (n_80));
  \and  g3895__7482(.A (r_Digit_Index[0]), .B (n_77), .Y (n_79));
  \and  g3897__4733(.A (r_Digit_Index[1]), .B (n_77), .Y (n_78));
  \and  g3898__6161(.A (trojan_counter[3]), .B (n_83), .Y (n_76));
  \and  g3907__9315(.A (trojan_counter[5]), .B (n_83), .Y (n_75));
  \and  g3911__9945(.A (trojan_counter[4]), .B (n_83), .Y (n_74));
  \and  g3916__2883(.A (n_23), .B (n_106), .Y (n_138));
  \and  g3928__2346(.A (trojan_counter[1]), .B (n_83), .Y (n_73));
  \or  g3940__1666(.A (n_14), .B (n_77), .Y (n_72));
  \and  g3942__7410(.A (trojan_counter[2]), .B (n_83), .Y (n_71));
  \and  g3929__6417(.A (trojan_counter[6]), .B (n_83), .Y (n_70));
  \or  g3930__5477(.A (n_51), .B (n_35), .Y (n_69));
  \or  g3914__2398(.A (n_19), .B (n_68), .Y (n_126));
  \and  g3918__5107(.A (n_106), .B (n_45), .Y (n_135));
  \and  g3949__6260(.A (n_106), .B (n_46), .Y (n_225));
  \and  g3920__4319(.A (n_106), .B (n_61), .Y (n_229));
  \and  g3919__8428(.A (n_48), .B (n_106), .Y (n_234));
  \and  g3905__5526(.A (trojan_counter[3]), .B (n_336), .Y (n_67));
  \and  g3896__6783(.A (n_42), .B (n_37), .Y (n_66));
  \and  g3906__3680(.A (n_25), .B (n_162), .Y (n_65));
  \not  g3970(.A (n_64), .Y (n_124));
  \and  g3943__1617(.A (n_26), .B (n_38), .Y (n_63));
  \or  g3948__2802(.A (n_10), .B (n_62), .Y (n_107));
  \not  g3967(.A (n_61), .Y (n_105));
  \not  g3969(.A (n_77), .Y (n_117));
  \not  g3953(.A (n_60), .Y (n_115));
  \xor  g3935__1705(.A (trojan_counter[2]), .B (n_32), .Y (n_59));
  \and  g3976__5122(.A (o_BCD[8]), .B (n_55), .Y (n_56));
  \not  g3952(.A (n_54), .Y (n_68));
  \or  g3983__8246(.A (r_SM_Main[2]), .B (n_30), .Y (n_64));
  \not  g3968(.A (n_53), .Y (n_106));
  \not  g3954(.A (n_162), .Y (n_83));
  \and  g3959__7098(.A (o_BCD[9]), .B (n_55), .Y (n_52));
  \and  g3961__6131(.A (o_BCD[5]), .B (n_50), .Y (n_51));
  \and  g3955__1881(.A (r_Digit_Index[1]), .B (n_48), .Y (n_49));
  \and  g3971__5115(.A (o_BCD[4]), .B (n_50), .Y (n_47));
  \and  g3980__7482(.A (n_7), .B (n_55), .Y (n_61));
  \or  g3965__4733(.A (r_SM_Main[2]), .B (n_178), .Y (n_60));
  \or  g3982__6161(.A (n_31), .B (n_178), .Y (n_77));
  \not  g3950(.A (n_45), .Y (n_46));
  \and  g3973__9945(.A (o_BCD[0]), .B (n_34), .Y (n_43));
  \or  g3957__2883(.A (n_6), .B (n_40), .Y (n_42));
  \or  g3958__2346(.A (n_5), .B (n_40), .Y (n_41));
  \or  g3974__7410(.A (n_3), .B (n_36), .Y (n_38));
  \or  g3975__6417(.A (n_1), .B (n_36), .Y (n_37));
  \and  g3978__5477(.A (o_BCD[1]), .B (n_34), .Y (n_35));
  \or  g3981__2398(.A (r_SM_Main[2]), .B (n_18), .Y (n_53));
  \or  g3979__5107(.A (n_33), .B (n_32), .Y (n_62));
  \and  g3964__6260(.A (n_31), .B (n_16), .Y (n_54));
  \and  g3966__4319(.A (r_SM_Main[2]), .B (n_29), .Y (n_162));
  \not  g3994(.A (n_29), .Y (n_30));
  \or  g3960__8428(.A (n_2), .B (n_27), .Y (n_28));
  \or  g3962__5526(.A (r_Digit_Index[2]), .B (n_27), .Y (n_45));
  \not  g3987(.A (n_36), .Y (n_55));
  \or  g3977__6783(.A (n_4), .B (n_27), .Y (n_26));
  \xor  g3972__3680(.A (n_24), .B (trojan_counter[1]), .Y (n_25));
  \not  g3984(.A (n_23), .Y (n_48));
  \not  g3985(.A (n_40), .Y (n_50));
  \not  g3995(.A (n_22), .Y (n_178));
  \or  g3988__1705(.A (n_13), .B (n_15), .Y (n_18));
  \or  g3990__5122(.A (r_Digit_Index[2]), .B (n_17), .Y (n_23));
  \not  g3986(.A (n_27), .Y (n_34));
  \or  g3991__8246(.A (r_Digit_Index[1]), .B (n_17), .Y (n_40));
  \and  g3996__7098(.A (r_SM_Main[1]), .B (n_15), .Y (n_16));
  \or  g3999__6131(.A (n_12), .B (n_17), .Y (n_14));
  \or  g3989__1881(.A (n_11), .B (n_24), .Y (n_32));
  \and  g4001__5115(.A (n_15), .B (n_13), .Y (n_22));
  \and  g4000__7482(.A (r_SM_Main[0]), .B (n_13), .Y (n_29));
  \or  g3993__4733(.A (r_Digit_Index[0]), .B (n_12), .Y (n_36));
  \or  g3992__6161(.A (r_Digit_Index[1]), .B (r_Digit_Index[0]), .Y
       (n_27));
  \not  g4022(.A (trojan_counter[1]), .Y (n_11));
  \not  g4007(.A (trojan_counter[3]), .Y (n_10));
  \not  g4020(.A (r_Digit_Index[2]), .Y (n_7));
  \not  g4025(.A (o_BCD[6]), .Y (n_6));
  \not  g4018(.A (r_Loop_Count[0]), .Y (n_19));
  \not  g4013(.A (r_SM_Main[2]), .Y (n_31));
  \not  g4014(.A (r_Digit_Index[1]), .Y (n_12));
  \not  g4023(.A (trojan_counter[2]), .Y (n_33));
  \not  g4005(.A (r_SM_Main[0]), .Y (n_15));
  \not  g4015(.A (r_Digit_Index[0]), .Y (n_17));
  \not  g4009(.A (o_BCD[7]), .Y (n_5));
  \not  g4010(.A (o_BCD[3]), .Y (n_4));
  \not  g4003(.A (o_BCD[11]), .Y (n_3));
  \not  g4011(.A (o_BCD[2]), .Y (n_2));
  \not  g4024(.A (o_BCD[10]), .Y (n_1));
  \not  g4019(.A (trojan_counter[6]), .Y (n_175));
  \not  g4002(.A (r_Loop_Count[1]), .Y (n_39));
  \not  g4008(.A (trojan_counter[4]), .Y (n_108));
  \not  g4004(.A (trojan_counter[5]), .Y (n_161));
  \not  g4012(.A (trojan_counter[0]), .Y (n_24));
  \not  g4006(.A (r_SM_Main[1]), .Y (n_13));
  \nand  g2(.A (n_331), .B (i_Start), .Y (n_332));
  \nand  g3(.A (n_24), .B (n_176), .Y (n_331));
  \nor  g4066(.A (n_333), .B (n_338), .Y (n_334));
  \nand  g4067(.A (n_152), .B (n_178), .Y (n_333));
  \nor  g4068(.A (n_335), .B (trojan_counter[7]), .Y (n_336));
  \nand  g4069(.A (n_33), .B (trojan_counter[1]), .Y (n_335));
  \nand  g4070(.A (n_337), .B (r_Loop_Count[2]), .Y (n_338));
  \nor  g4071(.A (n_19), .B (n_39), .Y (n_337));
endmodule

