
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Aug  8 2025 15:28:36 CST (Aug  8 2025 07:28:36 UTC)

// Verification Directory fv/design2302 

module design2302(i_Bus_Rst_L, i_Bus_Clk, i_Bus_CS, i_Bus_Wr_Rd_n,
     i_Bus_Addr8, i_Bus_Wr_Data, o_Bus_Rd_Data, o_Bus_Rd_DV,
     o_AC_Start, i_AC_Done);
  input i_Bus_Rst_L, i_Bus_Clk, i_Bus_CS, i_Bus_Wr_Rd_n;
  input [2:0] i_Bus_Addr8;
  input [7:0] i_Bus_Wr_Data;
  input [1:0] i_AC_Done;
  output [7:0] o_Bus_Rd_Data;
  output o_Bus_Rd_DV;
  output [1:0] o_AC_Start;
  wire i_Bus_Rst_L, i_Bus_Clk, i_Bus_CS, i_Bus_Wr_Rd_n;
  wire [2:0] i_Bus_Addr8;
  wire [7:0] i_Bus_Wr_Data;
  wire [1:0] i_AC_Done;
  wire [7:0] o_Bus_Rd_Data;
  wire o_Bus_Rd_DV;
  wire [1:0] o_AC_Start;
  wire [7:0] trojan_counter;
  wire [1:0] r_Reg_Stop;
  wire [1:0] r_Reg_Hist_Clear;
  wire [1:0] r_Reg_Start;
  wire [1:0] r_Reg_Hist_State;
  wire n_2, n_4, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_13, n_14, n_16, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_39, n_40;
  wire n_41, n_43, n_45, n_46, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_116, n_117;
  wire n_118, n_119, n_120, n_121, n_122, n_123, n_124, n_125;
  wire n_126, n_128, n_129, n_130, n_131, n_132, n_133, n_134;
  wire n_135, n_136, n_150, n_151, n_152, n_154, n_156, n_157;
  assign o_Bus_Rd_Data[2] = 1'b0;
  assign o_Bus_Rd_Data[3] = 1'b0;
  assign o_Bus_Rd_Data[4] = 1'b0;
  assign o_Bus_Rd_Data[5] = 1'b0;
  assign o_Bus_Rd_Data[6] = 1'b0;
  assign o_Bus_Rd_Data[7] = 1'b0;
  dff \o_Bus_Rd_Data_reg[0] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk),
       .D (n_135), .Q (o_Bus_Rd_Data[0]));
  dff \o_Bus_Rd_Data_reg[1] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk),
       .D (n_136), .Q (o_Bus_Rd_Data[1]));
  \or  g1627__2398(.A (n_132), .B (n_133), .Y (n_136));
  \or  g1626__5107(.A (n_131), .B (n_134), .Y (n_135));
  dff \trojan_counter_reg[7] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk),
       .D (n_130), .Q (trojan_counter[7]));
  \or  g1628__6260(.A (n_58), .B (n_129), .Y (n_134));
  \or  g1632__4319(.A (n_54), .B (n_128), .Y (n_133));
  \or  g1633__8428(.A (n_96), .B (n_123), .Y (n_132));
  \or  g1629__5526(.A (n_97), .B (n_125), .Y (n_131));
  \or  g1631__6783(.A (n_61), .B (n_124), .Y (n_130));
  dff \trojan_counter_reg[6] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk),
       .D (n_126), .Q (trojan_counter[6]));
  \and  g1634__3680(.A (o_AC_Start[0]), .B (n_152), .Y (n_129));
  \and  g1637__1617(.A (o_AC_Start[1]), .B (n_152), .Y (n_128));
  \or  g1635__2802(.A (n_57), .B (n_121), .Y (n_126));
  \and  g1638__1705(.A (r_Reg_Stop[0]), .B (n_122), .Y (n_125));
  \and  g1639__5122(.A (n_120), .B (n_119), .Y (n_124));
  \and  g1640__8246(.A (r_Reg_Stop[1]), .B (n_122), .Y (n_123));
  dff \trojan_counter_reg[5] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk),
       .D (n_118), .Q (trojan_counter[5]));
  dff \r_Reg_Stop_reg[0] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk), .D
       (n_116), .Q (r_Reg_Stop[0]));
  dff \r_Reg_Stop_reg[1] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk), .D
       (n_114), .Q (r_Reg_Stop[1]));
  \and  g1645__6131(.A (n_120), .B (n_109), .Y (n_121));
  \xor  g1646__1881(.A (trojan_counter[7]), .B (n_103), .Y (n_119));
  \or  g1641__5115(.A (n_68), .B (n_113), .Y (n_118));
  \and  g1647__7482(.A (n_117), .B (n_111), .Y (n_122));
  dff \trojan_counter_reg[4] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk),
       .D (n_112), .Q (trojan_counter[4]));
  \or  g1654__4733(.A (n_16), .B (n_104), .Y (n_116));
  dff \r_Reg_Hist_Clear_reg[0] (.RN (1'b1), .SN (1'b1), .CK
       (i_Bus_Clk), .D (n_106), .Q (r_Reg_Hist_Clear[0]));
  \or  g1657__9315(.A (n_23), .B (n_101), .Y (n_114));
  dff \r_Reg_Hist_Clear_reg[1] (.RN (1'b1), .SN (1'b1), .CK
       (i_Bus_Clk), .D (n_105), .Q (r_Reg_Hist_Clear[1]));
  \and  g1649__9945(.A (n_120), .B (n_99), .Y (n_113));
  \or  g1650__2883(.A (n_62), .B (n_94), .Y (n_112));
  \and  g1655__2346(.A (n_110), .B (n_107), .Y (n_111));
  \xor  g1658__1666(.A (trojan_counter[6]), .B (n_102), .Y (n_109));
  dff \trojan_counter_reg[3] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk),
       .D (n_98), .Q (trojan_counter[3]));
  \or  g1662__7410(.A (n_24), .B (n_93), .Y (n_106));
  \or  g1660__6417(.A (n_26), .B (n_90), .Y (n_105));
  \and  g1669__5477(.A (i_Bus_Wr_Data[0]), .B (n_100), .Y (n_104));
  \or  g1673__2398(.A (n_6), .B (n_102), .Y (n_103));
  \and  g1671__5107(.A (i_Bus_Wr_Data[1]), .B (n_100), .Y (n_101));
  dff \r_Reg_Start_reg[1] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk), .D
       (n_92), .Q (r_Reg_Start[1]));
  dff \r_Reg_Start_reg[0] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk), .D
       (n_91), .Q (r_Reg_Start[0]));
  \xor  g1667__6260(.A (trojan_counter[5]), .B (n_88), .Y (n_99));
  \or  g1661__4319(.A (n_65), .B (n_83), .Y (n_98));
  \and  g1668__8428(.A (r_Reg_Hist_State[0]), .B (n_95), .Y (n_97));
  dff \trojan_counter_reg[1] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk),
       .D (n_84), .Q (trojan_counter[1]));
  \and  g1670__5526(.A (r_Reg_Hist_State[1]), .B (n_95), .Y (n_96));
  \and  g1659__6783(.A (n_120), .B (n_85), .Y (n_94));
  \or  g1672__3680(.A (trojan_counter[6]), .B (n_87), .Y (n_107));
  dff \trojan_counter_reg[2] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk),
       .D (n_86), .Q (trojan_counter[2]));
  \and  g1674__1617(.A (i_Bus_Wr_Data[0]), .B (n_89), .Y (n_93));
  \or  g1682__2802(.A (n_82), .B (n_25), .Y (n_92));
  dff \r_Reg_Hist_State_reg[1] (.RN (i_Bus_Rst_L), .SN (1'b1), .CK
       (i_Bus_Clk), .D (n_78), .Q (r_Reg_Hist_State[1]));
  dff \r_Reg_State_reg[0] (.RN (i_Bus_Rst_L), .SN (1'b1), .CK
       (i_Bus_Clk), .D (n_77), .Q (o_AC_Start[0]));
  \or  g1685__1705(.A (n_81), .B (n_18), .Y (n_91));
  \and  g1683__5122(.A (i_Bus_Wr_Data[1]), .B (n_89), .Y (n_90));
  \and  g1687__8246(.A (i_Bus_Rst_L), .B (n_79), .Y (n_100));
  \or  g1689__7098(.A (n_7), .B (n_88), .Y (n_102));
  \or  g1676__6131(.A (trojan_counter[5]), .B (n_70), .Y (n_87));
  \or  g1675__1881(.A (n_63), .B (n_72), .Y (n_86));
  \xor  g1684__5115(.A (trojan_counter[4]), .B (n_76), .Y (n_85));
  dff \r_Reg_Hist_State_reg[0] (.RN (i_Bus_Rst_L), .SN (1'b1), .CK
       (i_Bus_Clk), .D (n_71), .Q (r_Reg_Hist_State[0]));
  \or  g1692__7482(.A (n_64), .B (n_73), .Y (n_84));
  \and  g1686__4733(.A (n_120), .B (n_74), .Y (n_83));
  dff \trojan_counter_reg[0] (.RN (1'b1), .SN (1'b1), .CK (i_Bus_Clk),
       .D (n_69), .Q (trojan_counter[0]));
  \and  g1688__6161(.A (i_Bus_Rst_L), .B (n_75), .Y (n_95));
  \and  g1700__9315(.A (i_Bus_Wr_Data[1]), .B (n_80), .Y (n_82));
  \and  g1698__9945(.A (i_Bus_Wr_Data[0]), .B (n_80), .Y (n_81));
  \and  g1702__2883(.A (i_Bus_Wr_Rd_n), .B (n_56), .Y (n_79));
  dff \r_Reg_State_reg[1] (.RN (i_Bus_Rst_L), .SN (1'b1), .CK
       (i_Bus_Clk), .D (n_55), .Q (o_AC_Start[1]));
  \or  g1690__2346(.A (r_Reg_Start[1]), .B (n_52), .Y (n_78));
  \or  g1697__1666(.A (r_Reg_Start[0]), .B (n_59), .Y (n_77));
  \and  g1695__7410(.A (i_Bus_Addr8[2]), .B (n_66), .Y (n_89));
  \or  g1704__6417(.A (n_11), .B (n_76), .Y (n_88));
  \and  g1701__5477(.A (n_40), .B (n_46), .Y (n_75));
  \xor  g1703__2398(.A (trojan_counter[3]), .B (n_60), .Y (n_74));
  \and  g1712__5107(.A (n_120), .B (n_32), .Y (n_73));
  \and  g1694__6260(.A (n_120), .B (n_45), .Y (n_72));
  \or  g1693__4319(.A (r_Reg_Start[0]), .B (n_48), .Y (n_71));
  \or  g1691__8428(.A (trojan_counter[4]), .B (n_49), .Y (n_70));
  \xor  g1699__5526(.A (trojan_counter[0]), .B (n_67), .Y (n_69));
  \and  g1711__6783(.A (trojan_counter[5]), .B (n_67), .Y (n_68));
  \and  g1706__3680(.A (n_37), .B (n_50), .Y (n_66));
  \and  g1707__1617(.A (trojan_counter[3]), .B (n_67), .Y (n_65));
  \and  g1709__2802(.A (trojan_counter[1]), .B (n_67), .Y (n_64));
  \and  g1705__1705(.A (trojan_counter[2]), .B (n_67), .Y (n_63));
  \and  g1710__5122(.A (trojan_counter[4]), .B (n_67), .Y (n_62));
  \and  g1713__8246(.A (trojan_counter[7]), .B (n_67), .Y (n_61));
  \or  g1715__7098(.A (n_13), .B (n_60), .Y (n_76));
  \and  g1716__6131(.A (o_AC_Start[0]), .B (n_39), .Y (n_59));
  \and  g1718__1881(.A (n_53), .B (o_Bus_Rd_Data[0]), .Y (n_58));
  \and  g1722__5115(.A (trojan_counter[6]), .B (n_67), .Y (n_57));
  \and  g1723__7482(.A (i_Bus_Addr8[1]), .B (n_51), .Y (n_56));
  \or  g1724__4733(.A (r_Reg_Start[1]), .B (n_156), .Y (n_55));
  \and  g1725__6161(.A (n_53), .B (o_Bus_Rd_Data[1]), .Y (n_54));
  \and  g1717__9315(.A (r_Reg_Hist_State[1]), .B (n_154), .Y (n_52));
  \and  g1726__9945(.A (i_Bus_Rst_L), .B (n_41), .Y (n_110));
  \and  g1727__2883(.A (n_51), .B (n_50), .Y (n_80));
  dff o_Bus_Rd_DV_reg(.RN (i_Bus_Rst_L), .SN (1'b1), .CK (i_Bus_Clk),
       .D (n_29), .Q (o_Bus_Rd_DV));
  \or  g1708__2346(.A (trojan_counter[3]), .B (n_34), .Y (n_49));
  \and  g1714__1666(.A (r_Reg_Hist_State[0]), .B (n_35), .Y (n_48));
  \and  g1720__7410(.A (i_Bus_Addr8[1]), .B (n_31), .Y (n_46));
  \xor  g1719__6417(.A (trojan_counter[2]), .B (n_43), .Y (n_45));
  \not  g1736(.A (n_67), .Y (n_120));
  \and  g1732__2398(.A (i_Bus_Rst_L), .B (n_22), .Y (n_50));
  \or  g1733__5107(.A (n_36), .B (n_28), .Y (n_53));
  \or  g1734__6260(.A (n_9), .B (n_43), .Y (n_60));
  \and  g1739__8428(.A (n_40), .B (n_20), .Y (n_41));
  \not  g1735(.A (n_33), .Y (n_39));
  \and  g1742__5526(.A (n_30), .B (n_37), .Y (n_51));
  \or  g1743__6783(.A (n_36), .B (n_150), .Y (n_67));
  \or  g1728__3680(.A (n_8), .B (n_33), .Y (n_35));
  \or  g1730__1617(.A (trojan_counter[7]), .B (n_14), .Y (n_34));
  \xor  g1737__2802(.A (n_21), .B (trojan_counter[1]), .Y (n_32));
  \and  g1738__1705(.A (n_30), .B (n_117), .Y (n_31));
  \not  g1752(.A (n_28), .Y (n_29));
  \and  g1745__8246(.A (n_36), .B (r_Reg_Hist_Clear[1]), .Y (n_26));
  \and  g1747__7098(.A (n_36), .B (r_Reg_Start[1]), .Y (n_25));
  \and  g1748__6131(.A (n_36), .B (r_Reg_Hist_Clear[0]), .Y (n_24));
  \and  g1749__1881(.A (n_36), .B (r_Reg_Stop[1]), .Y (n_23));
  \and  g1744__5115(.A (i_Bus_Wr_Rd_n), .B (n_19), .Y (n_22));
  \or  g1751__7482(.A (n_10), .B (n_21), .Y (n_43));
  \and  g1757__4733(.A (n_30), .B (n_19), .Y (n_20));
  \and  g1756__6161(.A (n_36), .B (r_Reg_Start[0]), .Y (n_18));
  \and  g1758__9945(.A (n_36), .B (r_Reg_Stop[0]), .Y (n_16));
  \or  g1759__2346(.A (i_Bus_Wr_Rd_n), .B (n_4), .Y (n_28));
  \and  g1760__1666(.A (i_Bus_CS), .B (n_2), .Y (n_37));
  \and  g1746__7410(.A (trojan_counter[2]), .B (trojan_counter[1]), .Y
       (n_14));
  \or  g1750__6417(.A (i_AC_Done[0]), .B (r_Reg_Stop[0]), .Y (n_33));
  \and  g1761__5477(.A (i_Bus_Addr8[0]), .B (i_Bus_CS), .Y (n_117));
  \not  g1767(.A (trojan_counter[3]), .Y (n_13));
  \not  g1766(.A (trojan_counter[4]), .Y (n_11));
  \not  g1778(.A (trojan_counter[1]), .Y (n_10));
  \not  g1769(.A (trojan_counter[2]), .Y (n_9));
  \not  g1763(.A (r_Reg_Hist_Clear[0]), .Y (n_8));
  \not  g1779(.A (i_Bus_Wr_Rd_n), .Y (n_40));
  \not  g1776(.A (trojan_counter[0]), .Y (n_21));
  \not  g1780(.A (i_Bus_Rst_L), .Y (n_36));
  \not  g1764(.A (trojan_counter[5]), .Y (n_7));
  \not  g1765(.A (trojan_counter[6]), .Y (n_6));
  \not  g1773(.A (i_Bus_CS), .Y (n_4));
  \not  g1771(.A (i_Bus_Addr8[0]), .Y (n_2));
  \not  g1777(.A (i_Bus_Addr8[1]), .Y (n_19));
  \not  g1774(.A (i_Bus_Addr8[2]), .Y (n_30));
  \nor  g2(.A (r_Reg_Start[1]), .B (r_Reg_Start[0]), .Y (n_150));
  \nor  g1804(.A (n_151), .B (n_107), .Y (n_152));
  \nand  g3(.A (n_117), .B (n_110), .Y (n_151));
  \nand  g1805(.A (n_157), .B (r_Reg_Hist_Clear[1]), .Y (n_154));
  \and  g1807(.A (n_157), .B (o_AC_Start[1]), .Y (n_156));
  \nor  g1809(.A (r_Reg_Stop[1]), .B (i_AC_Done[1]), .Y (n_157));
endmodule

