
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Aug  6 2025 00:57:04 CST (Aug  5 2025 16:57:04 UTC)

// Verification Directory fv/design1000 

module design1000(i_Clk, i_Binary_Num, o_Segment_A, o_Segment_B,
     o_Segment_C, o_Segment_D, o_Segment_E, o_Segment_F, o_Segment_G);
  input i_Clk;
  input [3:0] i_Binary_Num;
  output o_Segment_A, o_Segment_B, o_Segment_C, o_Segment_D,
       o_Segment_E, o_Segment_F, o_Segment_G;
  wire i_Clk;
  wire [3:0] i_Binary_Num;
  wire o_Segment_A, o_Segment_B, o_Segment_C, o_Segment_D, o_Segment_E,
       o_Segment_F, o_Segment_G;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  dff \r_Hex_Encoding_reg[2] (.RN (1'b1), .SN (1'b1), .CK (i_Clk), .D
       (n_46), .Q (o_Segment_E));
  \and  g778__2398(.A (n_9), .B (n_44), .Y (n_46));
  dff \r_Hex_Encoding_reg[3] (.RN (1'b1), .SN (1'b1), .CK (i_Clk), .D
       (n_45), .Q (o_Segment_D));
  \and  g780__5107(.A (n_10), .B (n_42), .Y (n_45));
  \or  g779__6260(.A (n_39), .B (n_43), .Y (n_44));
  dff \r_Hex_Encoding_reg[5] (.RN (1'b1), .SN (1'b1), .CK (i_Clk), .D
       (n_37), .Q (o_Segment_B));
  \and  g784__4319(.A (n_25), .B (n_41), .Y (n_43));
  \or  g785__8428(.A (n_40), .B (n_41), .Y (n_42));
  dff \r_Hex_Encoding_reg[6] (.RN (1'b1), .SN (1'b1), .CK (i_Clk), .D
       (n_36), .Q (o_Segment_A));
  dff \r_Hex_Encoding_reg[0] (.RN (1'b1), .SN (1'b1), .CK (i_Clk), .D
       (n_34), .Q (o_Segment_G));
  \and  g791__5526(.A (n_16), .B (n_38), .Y (n_40));
  \and  g787__6783(.A (n_20), .B (n_38), .Y (n_39));
  dff \r_Hex_Encoding_reg[1] (.RN (1'b1), .SN (1'b1), .CK (i_Clk), .D
       (n_33), .Q (o_Segment_F));
  \and  g789__3680(.A (n_35), .B (n_31), .Y (n_37));
  \and  g788__1617(.A (n_6), .B (n_38), .Y (n_41));
  \and  g792__2802(.A (n_35), .B (n_30), .Y (n_36));
  \and  g790__1705(.A (n_28), .B (n_32), .Y (n_34));
  \and  g794__5122(.A (n_27), .B (n_32), .Y (n_33));
  \and  g796__8246(.A (n_23), .B (n_26), .Y (n_31));
  \and  g795__7098(.A (n_29), .B (n_32), .Y (n_38));
  dff \r_Hex_Encoding_reg[4] (.RN (1'b1), .SN (1'b1), .CK (i_Clk), .D
       (n_24), .Q (o_Segment_C));
  \and  g797__6131(.A (n_21), .B (n_29), .Y (n_30));
  \or  g798__1881(.A (i_Binary_Num[1]), .B (n_22), .Y (n_28));
  \and  g802__5115(.A (n_5), .B (n_18), .Y (n_27));
  \or  g804__7482(.A (n_25), .B (n_17), .Y (n_26));
  \and  g801__4733(.A (n_7), .B (n_15), .Y (n_32));
  \and  g803__6161(.A (n_14), .B (n_23), .Y (n_24));
  \or  g805__9315(.A (i_Binary_Num[0]), .B (n_19), .Y (n_22));
  \or  g799__9945(.A (n_20), .B (n_19), .Y (n_21));
  \or  g800__2883(.A (i_Binary_Num[1]), .B (n_12), .Y (n_29));
  \or  g806__2346(.A (n_11), .B (n_20), .Y (n_18));
  \and  g808__1666(.A (n_16), .B (n_20), .Y (n_17));
  \or  g813__7410(.A (n_13), .B (n_20), .Y (n_15));
  \or  g809__6417(.A (n_13), .B (n_16), .Y (n_14));
  \or  g807__5477(.A (i_Binary_Num[0]), .B (n_25), .Y (n_12));
  \or  g810__2398(.A (n_11), .B (n_4), .Y (n_23));
  \and  g811__5107(.A (n_11), .B (n_13), .Y (n_19));
  \or  g815__6260(.A (n_11), .B (n_8), .Y (n_10));
  \or  g814__4319(.A (n_8), .B (n_13), .Y (n_9));
  \or  g812__8428(.A (n_8), .B (n_25), .Y (n_7));
  \or  g817__5526(.A (n_8), .B (n_6), .Y (n_35));
  \or  g816__6783(.A (n_3), .B (n_13), .Y (n_5));
  \not  g821(.A (n_4), .Y (n_20));
  \or  g822__3680(.A (i_Binary_Num[2]), .B (n_1), .Y (n_6));
  \or  g823__1617(.A (n_0), .B (n_3), .Y (n_8));
  \or  g824__2802(.A (i_Binary_Num[3]), .B (n_2), .Y (n_25));
  \and  g825__1705(.A (i_Binary_Num[0]), .B (n_3), .Y (n_4));
  \or  g818__5122(.A (i_Binary_Num[0]), .B (n_3), .Y (n_16));
  \or  g819__8246(.A (n_2), .B (n_1), .Y (n_11));
  \or  g820__7098(.A (i_Binary_Num[2]), .B (i_Binary_Num[3]), .Y
       (n_13));
  \not  g827(.A (i_Binary_Num[2]), .Y (n_2));
  \not  g829(.A (i_Binary_Num[1]), .Y (n_3));
  \not  g828(.A (i_Binary_Num[0]), .Y (n_0));
  \not  g826(.A (i_Binary_Num[3]), .Y (n_1));
endmodule

