
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Aug  5 2025 22:25:16 CST (Aug  5 2025 14:25:16 UTC)

// Verification Directory fv/design2000 

module design2000(i_Clk, i_Rst, i_Binary_Num, o_Segment_A, o_Segment_B,
     o_Segment_C, o_Segment_D, o_Segment_E, o_Segment_F, o_Segment_G);
  input i_Clk, i_Rst;
  input [3:0] i_Binary_Num;
  output o_Segment_A, o_Segment_B, o_Segment_C, o_Segment_D,
       o_Segment_E, o_Segment_F, o_Segment_G;
  wire i_Clk, i_Rst;
  wire [3:0] i_Binary_Num;
  wire o_Segment_A, o_Segment_B, o_Segment_C, o_Segment_D, o_Segment_E,
       o_Segment_F, o_Segment_G;
  wire [23:0] trojan_counter;
  wire [1:0] payload_timer;
  wire inc_add_34_46_n_255, inc_add_34_46_n_258, inc_add_34_46_n_261,
       inc_add_34_46_n_264, inc_add_34_46_n_267, inc_add_34_46_n_270,
       inc_add_34_46_n_273, inc_add_34_46_n_276;
  wire inc_add_34_46_n_279, inc_add_34_46_n_282, inc_add_34_46_n_285,
       inc_add_34_46_n_288, inc_add_34_46_n_291, inc_add_34_46_n_294,
       inc_add_34_46_n_297, inc_add_34_46_n_300;
  wire inc_add_34_46_n_303, inc_add_34_46_n_306, inc_add_34_46_n_309,
       inc_add_34_46_n_312, inc_add_34_46_n_315, inc_add_34_46_n_317,
       inc_add_34_46_n_319, inc_add_34_46_n_321;
  wire inc_add_34_46_n_323, inc_add_34_46_n_325, inc_add_34_46_n_326,
       inc_add_34_46_n_328, inc_add_34_46_n_330, inc_add_34_46_n_332,
       inc_add_34_46_n_334, inc_add_34_46_n_336;
  wire inc_add_34_46_n_340, inc_add_34_46_n_342, inc_add_34_46_n_344,
       inc_add_34_46_n_346, inc_add_34_46_n_348, inc_add_34_46_n_350,
       inc_add_34_46_n_352, inc_add_34_46_n_354;
  wire inc_add_34_46_n_356, inc_add_34_46_n_358, inc_add_34_46_n_360,
       n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_88;
  wire n_89, n_91, n_92, n_94, n_95, n_96, n_97, n_98;
  wire n_99, n_100, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_140, n_141, n_142, n_146, n_147, n_148, n_149;
  wire n_150, n_151, n_152, n_153, n_154, n_155, n_156, n_157;
  wire n_158, n_159, n_160, n_161, n_162, n_163, n_164, n_165;
  wire n_166, n_167, n_174, n_175, n_176, n_177, trojan_active;
  assign o_Segment_F = 1'b0;
  assign o_Segment_E = 1'b0;
  assign o_Segment_D = 1'b0;
  assign o_Segment_C = 1'b0;
  assign o_Segment_B = 1'b0;
  \not  g831(.A (i_Rst), .Y (n_142));
  dff trojan_active_reg(.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_141), .Q (trojan_active));
  dff \trojan_counter_reg[9] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_140), .Q (trojan_counter[9]));
  dff \trojan_counter_reg[4] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_134), .Q (trojan_counter[4]));
  dff \trojan_counter_reg[5] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_139), .Q (trojan_counter[5]));
  dff \trojan_counter_reg[6] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_137), .Q (trojan_counter[6]));
  dff \trojan_counter_reg[7] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_136), .Q (trojan_counter[7]));
  dff \trojan_counter_reg[8] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_135), .Q (trojan_counter[8]));
  dff \trojan_counter_reg[3] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_116), .Q (trojan_counter[3]));
  dff \trojan_counter_reg[10] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_131), .Q (trojan_counter[10]));
  dff \trojan_counter_reg[11] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_133), .Q (trojan_counter[11]));
  dff \trojan_counter_reg[12] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_132), .Q (trojan_counter[12]));
  dff \trojan_counter_reg[13] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_130), .Q (trojan_counter[13]));
  dff \trojan_counter_reg[14] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_129), .Q (trojan_counter[14]));
  \or  g1700__2398(.A (n_73), .B (n_138), .Y (n_141));
  dff \trojan_counter_reg[15] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_128), .Q (trojan_counter[15]));
  dff \trojan_counter_reg[16] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_127), .Q (trojan_counter[16]));
  dff \trojan_counter_reg[17] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_125), .Q (trojan_counter[17]));
  dff \trojan_counter_reg[18] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_124), .Q (trojan_counter[18]));
  dff \trojan_counter_reg[19] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_123), .Q (trojan_counter[19]));
  dff \trojan_counter_reg[20] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_122), .Q (trojan_counter[20]));
  dff \trojan_counter_reg[21] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_121), .Q (trojan_counter[21]));
  dff \trojan_counter_reg[1] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_118), .Q (trojan_counter[1]));
  dff \trojan_counter_reg[22] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_120), .Q (trojan_counter[22]));
  dff \trojan_counter_reg[23] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_119), .Q (trojan_counter[23]));
  dff \trojan_counter_reg[2] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_117), .Q (trojan_counter[2]));
  dff \trojan_counter_reg[0] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_126), .Q (trojan_counter[0]));
  \and  g1713__5107(.A (n_75), .B (n_115), .Y (n_140));
  \and  g1714__6260(.A (n_82), .B (n_115), .Y (n_139));
  \and  g1715__4319(.A (n_1), .B (n_114), .Y (n_138));
  \and  g1716__8428(.A (n_81), .B (n_115), .Y (n_137));
  \and  g1717__5526(.A (n_79), .B (n_115), .Y (n_136));
  \and  g1718__6783(.A (n_77), .B (n_115), .Y (n_135));
  \and  g1719__3680(.A (n_70), .B (n_115), .Y (n_134));
  \and  g1720__1617(.A (n_115), .B (n_72), .Y (n_133));
  \and  g1721__2802(.A (n_115), .B (n_71), .Y (n_132));
  \and  g1722__1705(.A (n_115), .B (n_74), .Y (n_131));
  \and  g1723__5122(.A (n_115), .B (n_62), .Y (n_130));
  \and  g1724__8246(.A (n_115), .B (n_68), .Y (n_129));
  \and  g1725__7098(.A (n_115), .B (n_67), .Y (n_128));
  \and  g1726__6131(.A (n_115), .B (n_83), .Y (n_127));
  \and  g1727__1881(.A (n_55), .B (n_115), .Y (n_126));
  \and  g1728__5115(.A (n_115), .B (n_65), .Y (n_125));
  \and  g1729__7482(.A (n_115), .B (n_76), .Y (n_124));
  \and  g1730__4733(.A (n_115), .B (n_60), .Y (n_123));
  \and  g1731__6161(.A (n_115), .B (n_66), .Y (n_122));
  \and  g1732__9315(.A (n_115), .B (n_69), .Y (n_121));
  \and  g1733__9945(.A (n_115), .B (n_64), .Y (n_120));
  \and  g1734__2883(.A (n_115), .B (n_61), .Y (n_119));
  \and  g1735__2346(.A (n_59), .B (n_115), .Y (n_118));
  \and  g1736__1666(.A (n_58), .B (n_115), .Y (n_117));
  \and  g1737__7410(.A (n_57), .B (n_115), .Y (n_116));
  \not  g1738(.A (n_114), .Y (n_115));
  \and  g1739__6417(.A (trojan_counter[0]), .B (n_113), .Y (n_114));
  \and  g1740__5477(.A (trojan_counter[19]), .B (n_112), .Y (n_113));
  \and  g1741__2398(.A (trojan_counter[16]), .B (n_111), .Y (n_112));
  \and  g1742__5107(.A (trojan_counter[15]), .B (n_110), .Y (n_111));
  \and  g1743__6260(.A (trojan_counter[7]), .B (n_109), .Y (n_110));
  \and  g1744__4319(.A (trojan_counter[22]), .B (n_108), .Y (n_109));
  \and  g1745__8428(.A (trojan_counter[20]), .B (n_107), .Y (n_108));
  \and  g1746__5526(.A (trojan_counter[10]), .B (n_106), .Y (n_107));
  \and  g1747__6783(.A (trojan_counter[8]), .B (n_105), .Y (n_106));
  \and  g1748__3680(.A (trojan_counter[6]), .B (n_104), .Y (n_105));
  \and  g1749__1617(.A (trojan_counter[4]), .B (n_103), .Y (n_104));
  \and  g1750__2802(.A (trojan_counter[23]), .B (n_102), .Y (n_103));
  \and  g1751__1705(.A (trojan_counter[18]), .B (n_101), .Y (n_102));
  \and  g1752__5122(.A (trojan_counter[14]), .B (n_100), .Y (n_101));
  \and  g1753__8246(.A (trojan_counter[12]), .B (n_99), .Y (n_100));
  \and  g1754__7098(.A (trojan_counter[2]), .B (n_98), .Y (n_99));
  dff \r_Hex_Encoding_reg[0] (.RN (1'b1), .SN (1'b1), .CK (i_Clk), .D
       (n_96), .Q (o_Segment_G));
  \and  g1756__6131(.A (trojan_counter[1]), .B (n_95), .Y (n_98));
  dff \r_Hex_Encoding_reg[6] (.RN (1'b1), .SN (1'b1), .CK (i_Clk), .D
       (n_97), .Q (o_Segment_A));
  \and  g1758__1881(.A (n_1), .B (n_175), .Y (n_97));
  \and  g1759__5115(.A (n_1), .B (n_94), .Y (n_96));
  \and  g1760__7482(.A (trojan_counter[21]), .B (n_92), .Y (n_95));
  \or  g1761__4733(.A (n_88), .B (n_91), .Y (n_94));
  \and  g1763__9315(.A (trojan_counter[11]), .B (n_89), .Y (n_92));
  \and  g1764__9945(.A (n_86), .B (o_Segment_G), .Y (n_91));
  dff \payload_timer_reg[1] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_84), .Q (payload_timer[1]));
  \and  g1767__2346(.A (trojan_counter[3]), .B (n_85), .Y (n_89));
  \and  g1768__1666(.A (i_Binary_Num[3]), .B (n_80), .Y (n_88));
  dff \payload_timer_reg[0] (.RN (n_142), .SN (1'b1), .CK (i_Clk), .D
       (n_56), .Q (payload_timer[0]));
  \and  g1771__7410(.A (trojan_counter[5]), .B (n_63), .Y (n_85));
  \xor  g1772__6417(.A (payload_timer[1]), .B (n_4), .Y (n_84));
  \or  g1773__5477(.A (i_Binary_Num[0]), .B (n_78), .Y (n_86));
  \or  g1774__2398(.A (n_22), .B (n_21), .Y (n_83));
  \or  g1775__5107(.A (n_47), .B (n_46), .Y (n_82));
  \or  g1776__6260(.A (n_44), .B (n_48), .Y (n_81));
  \and  g1777__4319(.A (i_Binary_Num[2]), .B (n_41), .Y (n_80));
  \or  g1778__8428(.A (n_43), .B (n_54), .Y (n_79));
  \or  g1779__5526(.A (i_Binary_Num[1]), .B (n_38), .Y (n_78));
  \or  g1780__6783(.A (n_39), .B (n_32), .Y (n_77));
  \or  g1781__3680(.A (n_19), .B (n_52), .Y (n_76));
  \or  g1782__1617(.A (n_40), .B (n_36), .Y (n_75));
  \or  g1783__2802(.A (n_33), .B (n_34), .Y (n_74));
  \and  g1784__1705(.A (trojan_active), .B (n_30), .Y (n_73));
  \or  g1785__5122(.A (n_18), .B (n_16), .Y (n_72));
  \or  g1786__8246(.A (n_27), .B (n_23), .Y (n_71));
  \or  g1787__7098(.A (n_35), .B (n_50), .Y (n_70));
  \or  g1788__6131(.A (n_45), .B (n_9), .Y (n_69));
  \or  g1789__1881(.A (n_7), .B (n_6), .Y (n_68));
  \or  g1790__5115(.A (n_13), .B (n_20), .Y (n_67));
  \or  g1791__7482(.A (n_15), .B (n_12), .Y (n_66));
  \or  g1792__4733(.A (n_28), .B (n_53), .Y (n_65));
  \or  g1793__6161(.A (n_31), .B (n_26), .Y (n_64));
  \and  g1794__9315(.A (trojan_counter[9]), .B (n_14), .Y (n_63));
  \or  g1795__9945(.A (n_25), .B (n_24), .Y (n_62));
  \or  g1796__2883(.A (trojan_counter[23]), .B (n_177), .Y (n_61));
  \or  g1797__2346(.A (n_11), .B (n_29), .Y (n_60));
  \or  g1798__1666(.A (n_10), .B (n_8), .Y (n_59));
  \or  g1799__7410(.A (n_5), .B (n_17), .Y (n_58));
  \or  g1800__6417(.A (n_42), .B (n_51), .Y (n_57));
  \xor  g1801__5477(.A (n_2), .B (trojan_active), .Y (n_56));
  \xor  g1802__2398(.A (trojan_active), .B (trojan_counter[0]), .Y
       (n_55));
  \and  g1803__5107(.A (n_1), .B (n_161), .Y (n_54));
  \and  g1804__6260(.A (n_1), .B (n_151), .Y (n_53));
  \and  g1805__4319(.A (n_1), .B (n_150), .Y (n_52));
  \and  g1806__8428(.A (n_1), .B (n_165), .Y (n_51));
  \and  g1807__5526(.A (n_1), .B (n_164), .Y (n_50));
  \and  g1809__3680(.A (n_1), .B (n_162), .Y (n_48));
  \and  g1810__1617(.A (trojan_counter[5]), .B (trojan_active), .Y
       (n_47));
  \and  g1811__2802(.A (n_1), .B (n_163), .Y (n_46));
  \and  g1812__1705(.A (trojan_counter[21]), .B (trojan_active), .Y
       (n_45));
  \and  g1813__5122(.A (trojan_counter[6]), .B (trojan_active), .Y
       (n_44));
  \and  g1814__8246(.A (trojan_counter[7]), .B (trojan_active), .Y
       (n_43));
  \and  g1815__7098(.A (trojan_counter[3]), .B (trojan_active), .Y
       (n_42));
  \and  g1816__6131(.A (i_Binary_Num[0]), .B (i_Binary_Num[1]), .Y
       (n_41));
  \and  g1817__1881(.A (trojan_counter[9]), .B (trojan_active), .Y
       (n_40));
  \and  g1818__5115(.A (trojan_counter[8]), .B (trojan_active), .Y
       (n_39));
  \or  g1819__7482(.A (i_Binary_Num[2]), .B (i_Binary_Num[3]), .Y
       (n_38));
  \and  g1821__4733(.A (n_1), .B (n_159), .Y (n_36));
  \and  g1822__6161(.A (trojan_counter[4]), .B (trojan_active), .Y
       (n_35));
  \and  g1823__9315(.A (n_1), .B (n_158), .Y (n_34));
  \and  g1824__9945(.A (trojan_counter[10]), .B (trojan_active), .Y
       (n_33));
  \and  g1825__2883(.A (n_1), .B (n_160), .Y (n_32));
  \and  g1826__2346(.A (trojan_counter[22]), .B (trojan_active), .Y
       (n_31));
  \or  g1827__1666(.A (n_3), .B (n_2), .Y (n_30));
  \and  g1828__7410(.A (n_1), .B (n_149), .Y (n_29));
  \and  g1829__6417(.A (trojan_counter[17]), .B (trojan_active), .Y
       (n_28));
  \and  g1830__5477(.A (trojan_counter[12]), .B (trojan_active), .Y
       (n_27));
  \and  g1831__2398(.A (n_1), .B (n_146), .Y (n_26));
  \and  g1832__5107(.A (trojan_counter[13]), .B (trojan_active), .Y
       (n_25));
  \and  g1833__6260(.A (n_1), .B (n_155), .Y (n_24));
  \and  g1834__4319(.A (n_1), .B (n_156), .Y (n_23));
  \and  g1835__8428(.A (trojan_counter[16]), .B (trojan_active), .Y
       (n_22));
  \and  g1836__5526(.A (n_1), .B (n_152), .Y (n_21));
  \and  g1837__6783(.A (n_1), .B (n_153), .Y (n_20));
  \and  g1838__3680(.A (trojan_counter[18]), .B (trojan_active), .Y
       (n_19));
  \and  g1839__1617(.A (trojan_counter[11]), .B (trojan_active), .Y
       (n_18));
  \and  g1840__2802(.A (n_1), .B (n_166), .Y (n_17));
  \and  g1841__1705(.A (n_1), .B (n_157), .Y (n_16));
  \and  g1842__5122(.A (trojan_counter[20]), .B (trojan_active), .Y
       (n_15));
  \and  g1843__8246(.A (trojan_counter[17]), .B (trojan_counter[13]),
       .Y (n_14));
  \and  g1844__7098(.A (trojan_counter[15]), .B (trojan_active), .Y
       (n_13));
  \and  g1845__6131(.A (n_1), .B (n_148), .Y (n_12));
  \and  g1846__1881(.A (trojan_counter[19]), .B (trojan_active), .Y
       (n_11));
  \and  g1847__5115(.A (trojan_counter[1]), .B (trojan_active), .Y
       (n_10));
  \and  g1848__7482(.A (n_1), .B (n_147), .Y (n_9));
  \and  g1849__4733(.A (n_1), .B (n_167), .Y (n_8));
  \and  g1850__6161(.A (trojan_counter[14]), .B (trojan_active), .Y
       (n_7));
  \and  g1851__9315(.A (n_1), .B (n_154), .Y (n_6));
  \and  g1852__9945(.A (trojan_counter[2]), .B (trojan_active), .Y
       (n_5));
  \or  g1853__2883(.A (n_2), .B (n_1), .Y (n_4));
  \not  g1854(.A (payload_timer[1]), .Y (n_3));
  \not  g1855(.A (payload_timer[0]), .Y (n_2));
  \not  g1856(.A (trojan_active), .Y (n_1));
  \xor  inc_add_34_46_g396__2346(.A (trojan_counter[22]), .B
       (inc_add_34_46_n_255), .Y (n_146));
  \xor  inc_add_34_46_g398__7410(.A (trojan_counter[21]), .B
       (inc_add_34_46_n_258), .Y (n_147));
  \or  inc_add_34_46_g399__6417(.A (inc_add_34_46_n_360), .B
       (inc_add_34_46_n_258), .Y (inc_add_34_46_n_255));
  \xor  inc_add_34_46_g400__5477(.A (trojan_counter[20]), .B
       (inc_add_34_46_n_261), .Y (n_148));
  \or  inc_add_34_46_g401__2398(.A (inc_add_34_46_n_330), .B
       (inc_add_34_46_n_261), .Y (inc_add_34_46_n_258));
  \xor  inc_add_34_46_g402__5107(.A (trojan_counter[19]), .B
       (inc_add_34_46_n_264), .Y (n_149));
  \or  inc_add_34_46_g403__6260(.A (inc_add_34_46_n_321), .B
       (inc_add_34_46_n_264), .Y (inc_add_34_46_n_261));
  \xor  inc_add_34_46_g404__4319(.A (trojan_counter[18]), .B
       (inc_add_34_46_n_267), .Y (n_150));
  \or  inc_add_34_46_g405__8428(.A (inc_add_34_46_n_342), .B
       (inc_add_34_46_n_267), .Y (inc_add_34_46_n_264));
  \xor  inc_add_34_46_g406__5526(.A (trojan_counter[17]), .B
       (inc_add_34_46_n_270), .Y (n_151));
  \or  inc_add_34_46_g407__6783(.A (inc_add_34_46_n_356), .B
       (inc_add_34_46_n_270), .Y (inc_add_34_46_n_267));
  \xor  inc_add_34_46_g408__3680(.A (trojan_counter[16]), .B
       (inc_add_34_46_n_273), .Y (n_152));
  \or  inc_add_34_46_g409__1617(.A (inc_add_34_46_n_334), .B
       (inc_add_34_46_n_273), .Y (inc_add_34_46_n_270));
  \xor  inc_add_34_46_g410__2802(.A (trojan_counter[15]), .B
       (inc_add_34_46_n_276), .Y (n_153));
  \or  inc_add_34_46_g411__1705(.A (inc_add_34_46_n_354), .B
       (inc_add_34_46_n_276), .Y (inc_add_34_46_n_273));
  \xor  inc_add_34_46_g412__5122(.A (trojan_counter[14]), .B
       (inc_add_34_46_n_279), .Y (n_154));
  \or  inc_add_34_46_g413__8246(.A (inc_add_34_46_n_358), .B
       (inc_add_34_46_n_279), .Y (inc_add_34_46_n_276));
  \xor  inc_add_34_46_g414__7098(.A (trojan_counter[13]), .B
       (inc_add_34_46_n_282), .Y (n_155));
  \or  inc_add_34_46_g415__6131(.A (inc_add_34_46_n_317), .B
       (inc_add_34_46_n_282), .Y (inc_add_34_46_n_279));
  \xor  inc_add_34_46_g416__1881(.A (trojan_counter[12]), .B
       (inc_add_34_46_n_285), .Y (n_156));
  \or  inc_add_34_46_g417__5115(.A (inc_add_34_46_n_328), .B
       (inc_add_34_46_n_285), .Y (inc_add_34_46_n_282));
  \xor  inc_add_34_46_g418__7482(.A (trojan_counter[11]), .B
       (inc_add_34_46_n_288), .Y (n_157));
  \or  inc_add_34_46_g419__4733(.A (inc_add_34_46_n_326), .B
       (inc_add_34_46_n_288), .Y (inc_add_34_46_n_285));
  \xor  inc_add_34_46_g420__6161(.A (trojan_counter[10]), .B
       (inc_add_34_46_n_291), .Y (n_158));
  \or  inc_add_34_46_g421__9315(.A (inc_add_34_46_n_332), .B
       (inc_add_34_46_n_291), .Y (inc_add_34_46_n_288));
  \xor  inc_add_34_46_g422__9945(.A (trojan_counter[9]), .B
       (inc_add_34_46_n_294), .Y (n_159));
  \or  inc_add_34_46_g423__2883(.A (inc_add_34_46_n_319), .B
       (inc_add_34_46_n_294), .Y (inc_add_34_46_n_291));
  \xor  inc_add_34_46_g424__2346(.A (trojan_counter[8]), .B
       (inc_add_34_46_n_297), .Y (n_160));
  \or  inc_add_34_46_g425__1666(.A (inc_add_34_46_n_348), .B
       (inc_add_34_46_n_297), .Y (inc_add_34_46_n_294));
  \xor  inc_add_34_46_g426__7410(.A (trojan_counter[7]), .B
       (inc_add_34_46_n_300), .Y (n_161));
  \or  inc_add_34_46_g427__6417(.A (inc_add_34_46_n_323), .B
       (inc_add_34_46_n_300), .Y (inc_add_34_46_n_297));
  \xor  inc_add_34_46_g428__5477(.A (trojan_counter[6]), .B
       (inc_add_34_46_n_303), .Y (n_162));
  \or  inc_add_34_46_g429__2398(.A (inc_add_34_46_n_340), .B
       (inc_add_34_46_n_303), .Y (inc_add_34_46_n_300));
  \xor  inc_add_34_46_g430__5107(.A (trojan_counter[5]), .B
       (inc_add_34_46_n_306), .Y (n_163));
  \or  inc_add_34_46_g431__6260(.A (inc_add_34_46_n_350), .B
       (inc_add_34_46_n_306), .Y (inc_add_34_46_n_303));
  \xor  inc_add_34_46_g432__4319(.A (trojan_counter[4]), .B
       (inc_add_34_46_n_309), .Y (n_164));
  \or  inc_add_34_46_g433__8428(.A (inc_add_34_46_n_352), .B
       (inc_add_34_46_n_309), .Y (inc_add_34_46_n_306));
  \xor  inc_add_34_46_g434__5526(.A (trojan_counter[3]), .B
       (inc_add_34_46_n_312), .Y (n_165));
  \or  inc_add_34_46_g435__6783(.A (inc_add_34_46_n_346), .B
       (inc_add_34_46_n_312), .Y (inc_add_34_46_n_309));
  \xor  inc_add_34_46_g436__3680(.A (trojan_counter[2]), .B
       (inc_add_34_46_n_315), .Y (n_166));
  \or  inc_add_34_46_g437__1617(.A (inc_add_34_46_n_336), .B
       (inc_add_34_46_n_315), .Y (inc_add_34_46_n_312));
  \xor  inc_add_34_46_g438__2802(.A (trojan_counter[0]), .B
       (inc_add_34_46_n_325), .Y (n_167));
  \or  inc_add_34_46_g439__1705(.A (inc_add_34_46_n_344), .B
       (inc_add_34_46_n_325), .Y (inc_add_34_46_n_315));
  \not  inc_add_34_46_g440(.A (trojan_counter[13]), .Y
       (inc_add_34_46_n_317));
  \not  inc_add_34_46_g441(.A (trojan_counter[9]), .Y
       (inc_add_34_46_n_319));
  \not  inc_add_34_46_g442(.A (trojan_counter[19]), .Y
       (inc_add_34_46_n_321));
  \not  inc_add_34_46_g443(.A (trojan_counter[7]), .Y
       (inc_add_34_46_n_323));
  \not  inc_add_34_46_g444(.A (trojan_counter[1]), .Y
       (inc_add_34_46_n_325));
  \not  inc_add_34_46_g445(.A (trojan_counter[11]), .Y
       (inc_add_34_46_n_326));
  \not  inc_add_34_46_g446(.A (trojan_counter[12]), .Y
       (inc_add_34_46_n_328));
  \not  inc_add_34_46_g447(.A (trojan_counter[20]), .Y
       (inc_add_34_46_n_330));
  \not  inc_add_34_46_g448(.A (trojan_counter[10]), .Y
       (inc_add_34_46_n_332));
  \not  inc_add_34_46_g449(.A (trojan_counter[16]), .Y
       (inc_add_34_46_n_334));
  \not  inc_add_34_46_g450(.A (trojan_counter[2]), .Y
       (inc_add_34_46_n_336));
  \not  inc_add_34_46_g452(.A (trojan_counter[6]), .Y
       (inc_add_34_46_n_340));
  \not  inc_add_34_46_g453(.A (trojan_counter[18]), .Y
       (inc_add_34_46_n_342));
  \not  inc_add_34_46_g454(.A (trojan_counter[0]), .Y
       (inc_add_34_46_n_344));
  \not  inc_add_34_46_g455(.A (trojan_counter[3]), .Y
       (inc_add_34_46_n_346));
  \not  inc_add_34_46_g456(.A (trojan_counter[8]), .Y
       (inc_add_34_46_n_348));
  \not  inc_add_34_46_g457(.A (trojan_counter[5]), .Y
       (inc_add_34_46_n_350));
  \not  inc_add_34_46_g458(.A (trojan_counter[4]), .Y
       (inc_add_34_46_n_352));
  \not  inc_add_34_46_g459(.A (trojan_counter[15]), .Y
       (inc_add_34_46_n_354));
  \not  inc_add_34_46_g460(.A (trojan_counter[17]), .Y
       (inc_add_34_46_n_356));
  \not  inc_add_34_46_g461(.A (trojan_counter[14]), .Y
       (inc_add_34_46_n_358));
  \not  inc_add_34_46_g462(.A (trojan_counter[21]), .Y
       (inc_add_34_46_n_360));
  \nand  g1859(.A (n_174), .B (n_86), .Y (n_175));
  \nor  g3(.A (n_88), .B (o_Segment_A), .Y (n_174));
  \nor  g1860(.A (n_176), .B (inc_add_34_46_n_255), .Y (n_177));
  \nand  g1861(.A (n_1), .B (trojan_counter[22]), .Y (n_176));
endmodule

